update source

diff --git a/src/efs/templates/first-file-system.yml b/src/efs/templates/first-file-system.yml
--- a/src/efs/templates/first-file-system.yml
+++ b/src/efs/templates/first-file-system.yml
@@ -235,8 +235,8 @@ Resources:
       Roles:
         - Ref: EC2InstanceRole
 
-  EC2LaunchTemplate:
-    Type: AWS::EC2::LaunchTemplate
+  EC2Instance:
+    Type: AWS::EC2::Instance
     Metadata:
       AWS::CloudFormation::Init:
         config:
@@ -254,72 +254,51 @@ Resources:
                   sudo umount ${MountDir}
               mode: "000755"
     Properties:
-      LaunchTemplateName:
-        Fn::Sub: ${AWS::StackName}-EC2LaunchTemplate
-      VersionDescription: Launch template for EC2 instances
-      TagSpecifications:
-        - ResourceType: launch-template
-          Tags:
-            - Key: Name
-              Value: EC2LaunchTemplate
-      LaunchTemplateData:
-        ImageId:
-          Ref: ImageId
-        InstanceType:
-          Ref: InstanceType
-        IamInstanceProfile:
-          Name:
-            Ref: EC2InstanceProfile
-        SecurityGroupIds:
-          - Ref: EC2SecurityGroup
-        TagSpecifications:
-          - ResourceType: instance
-            Tags:
-              - Key: Name
-                Value: EC2Instance
-        UserData:
-          Fn::Base64:
-            Fn::Sub: |
-              #!/bin/sh
-              dnf update -y
-              dnf install -y amazon-efs-utils nfs-utils
-              mkdir -p ${MountDir}
-              /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource EC2LaunchTemplate --region ${AWS::Region}
-
-              # echo "${FileSystem}:${MountDir} efs tls,_netdev" >> /etc/fstab
-              # echo "${FileSystem}.efs.${AWS::Region}.amazonaws.com:${MountDir} nfs4 nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport,_netdev 0 0" >> /etc/fstab
-              # cat <<EOF >> /etc/amazon/efs/efs-utils.conf
-              # [client-info]
-              # source=liw
-              # EOF
-
-              # RETRY_COUNT=15
-              # WAIT_TIME=30
-              # while :; do
-              #     mount -a -t efs,nfs4 defaults
-              #     if [ "$?" -eq "0" ]; then
-              #         echo "File system mounted successfully"
-              #         break
-              #     fi
-              #     RETRY_COUNT=`expr -- $RETRY_COUNT - 1`
-              #     if [ "$RETRY_COUNT" -lt "1" ]; then
-              #         echo "Reached to retry limit, aborted." >&2
-              #         break
-              #     fi
-              #     echo "File system not available, retrying to mount."
-              #     sleep $WAIT_TIME
-              # done
-
-  EC2Instance:
-    Type: AWS::EC2::Instance
-    Properties:
-      LaunchTemplate:
-        LaunchTemplateId:
-          Ref: EC2LaunchTemplate
-        Version:
-          Fn::GetAtt: EC2LaunchTemplate.LatestVersionNumber
+      ImageId:
+        Ref: ImageId
+      InstanceType:
+        Ref: InstanceType
+      IamInstanceProfile:
+        Ref: EC2InstanceProfile
       SubnetId:
         Ref: Subnet0
+      SecurityGroupIds:
+        - Ref: EC2SecurityGroup
+      Tags:
+        - Key: Name
+          Value: EC2Instance
+      UserData:
+        Fn::Base64:
+          Fn::Sub: |
+            #!/bin/sh
+            dnf update -y
+            dnf install -y amazon-efs-utils nfs-utils
+            mkdir -p ${MountDir}
+            /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource EC2Instance --region ${AWS::Region}
+
+            # echo "${FileSystem}:${MountDir} efs tls,_netdev" >> /etc/fstab
+            # echo "${FileSystem}.efs.${AWS::Region}.amazonaws.com:${MountDir} nfs4 nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport,_netdev 0 0" >> /etc/fstab
+            # cat <<EOF >> /etc/amazon/efs/efs-utils.conf
+            # [client-info]
+            # source=liw
+            # EOF
+
+            # RETRY_COUNT=15
+            # WAIT_TIME=30
+            # while :; do
+            #     mount -a -t efs,nfs4 defaults
+            #     if [ "$?" -eq "0" ]; then
+            #         echo "File system mounted successfully"
+            #         break
+            #     fi
+            #     RETRY_COUNT=`expr -- $RETRY_COUNT - 1`
+            #     if [ "$RETRY_COUNT" -lt "1" ]; then
+            #         echo "Reached to retry limit, aborted." >&2
+            #         break
+            #     fi
+            #     echo "File system not available, retrying to mount."
+            #     sleep $WAIT_TIME
+            # done
 
   # EFS
   EFSSecurityGroup:
